const equipesList = [{
  numero: '1',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '1',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '1',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '1',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '1',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '1',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '1',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '1',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '1',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '1',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '1',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '1',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '1',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '1',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
];

export async function getEquipes() {
  return new Promise((resolve) => {
    setTimeout(() => resolve(equipesList), 300);
  });
}
