const equipesList = [{
  numero: '1',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '2',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '3',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '4',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '5',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '6',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '7',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '8',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '9',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '10',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '11',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '12',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '13',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
{
  numero: '14',
  nom: 'Caméléon',
  membre: 'Victor ELY',
  parcours: 'SI',
  technologie: 'yes',
  sujet: '1',
  status: 'validate',
},
];

export async function getEquipes() {
  return new Promise((resolve) => {
    setTimeout(() => resolve(equipesList), 300);
  });
}
